version: '3.9'
services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    hostname: azurite
    restart: always
    command: "azurite --tableHost 127.0.0.1 --tablePort 10002"
    ports:
      - "10002:10002"

  lebowski-bot:
    build: .
    command: "pytest --cov=mybot/lebowski"
