name: Deployment To Production

on:
  push:
    branches: [ master ]

jobs:
  run_unit_tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    env:
        StorageAccountConnectionString: ${{ secrets.STORAGEACCOUNTCONNECTIONSTRING_LOCAL }}
    services:
      azure-table-emulator:
        image: mcr.microsoft.com/azure-storage/azurite
        ports:
          - 10002:10002
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r mybot/requirements.txt
    - name: Test
      run: pytest -o log_cli=True --cov=./mybot/lebowski ./mybot --junit-xml pytest.xml
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()

  Publish:
    needs: [run_unit_tests]
    runs-on: ubuntu-latest
    env:
      AZURE_FUNCTIONAPP_PACKAGE_PATH: './mybot' # set this to the path to your web app project, defaults to the repository root
      PYTHON_VERSION: '3.9' # set this to the python version to use (supports 3.6, 3.7, 3.8)
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2
    - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
      uses: actions/setup-python@v1
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: 'Resolve Project Dependencies Using Pip'
      shell: bash
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        python -m pip install --upgrade pip
        pip install -r requirements.txt --target=".python_packages/lib/site-packages"
        popd

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: 'lebowski-bot'
        slot-name: 'production'
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        scm-do-build-during-deployment: true
        enable-oryx-build: true
