name: Publish on Docker Hub and Deploy

on:
  push:
    branches: [ master ]

jobs:
  Publish:
    runs-on: [ubuntu-latest]
    env:
        DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
        DOCKERHUB_REPOSITORY: ${{ secrets.DOCKERHUB_REPOSITORY }}
    steps:
    - name: Login to docker.io
      run:  echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USER }} --password-stdin
    - uses: actions/checkout@master
    - name: Build image
      run: docker build -t $DOCKERHUB_USER/$DOCKERHUB_REPOSITORY:latest -t $DOCKERHUB_USER/$DOCKERHUB_REPOSITORY:${GITHUB_REF##*/}-${{ github.run_number }} -f mybot/Dockerfile mybot
    - name: Push image to docker.io
      run: docker push $DOCKERHUB_USER/$DOCKERHUB_REPOSITORY --all-tags   