name: Check Pull-Request

on: pull_request

jobs:
  run-unit-tests:
    name: Unit Tests Run
    runs-on: ubuntu-latest
    env:
        StorageAccountConnectionString: ${{ secrets.STORAGEACCOUNTCONNECTIONSTRING_LOCAL }}
    services:
      azure-table-emulator:
        image: mcr.microsoft.com/azure-storage/azurite
        ports:
          - 10002:10002
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r mybot/requirements.txt
    - name: Test
      run: pytest -o log_cli=True --cov=./mybot/lebowski ./mybot --junit-xml pytest.xml
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()